title: Janhavi Sathe's Home
author: [janhavi-sathe](https://github.com/janhavi-sathe)
description: > # this means to ignore newlines until "baseurl:"
  Janhavi's first blog using GitHub Pages!

# social links
github_username:  janhavi-sathe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: feeling-responsive
